spring:
  datasource:
    url: jdbc:mysql://my-db:3306/mydb
    username: root
    password: enddl314**
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: my-cache-server
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: debug